<a href="https://colab.research.google.com/github/hvjha/AWA/blob/Python/class_22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
l1 = [1,2,3]
l2 = [2,3,4]

In [ ]:
l1 + l2

[1, 2, 3, 2, 3, 4]

In [ ]:
list1 = [1,2,3]
list2 = [2,4,5]
result = [list1[i] + list2[i] for i in range(len(list1))]
print(result)

[3, 6, 8]


In [ ]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([2,4,5])

result = (arr1 + arr2)
print(result)

[3 6 8]


In [ ]:
arr1 = np.array([1,2,3])
print(arr1)

[1 2 3]


In [ ]:
arr2 = np.array([[1,2,3],[2,4,5]])
print(arr2)

[[1 2 3]
 [2 4 5]]


In [ ]:
arr2.shape

(2, 3)

In [ ]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[3,4,5],[6,7,8]],[[6,7,8],[9,7,4]]])
print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[3 4 5]
  [6 7 8]]

 [[6 7 8]
  [9 7 4]]]


In [ ]:
arr3.shape

(3, 2, 3)

In [ ]:
#initialize the array
zeros = np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
random_arr = np.ceil(np.random.rand(2,3)*10).astype(int)
print(random_arr)

[[ 4  2 10]
 [ 5  6  5]]


In [ ]:
ones = np.ones((2,4,5))
print(ones)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [ ]:
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
import numpy as np

In [ ]:
range_arr = np.arange(0,10,2)
print(range_arr)

[0 2 4 6 8]


In [ ]:
arr = np.array([10,20,30,40,50])
print(arr.shape)
print(arr.size)

(5,)
5


In [ ]:
arr[-2]

np.int64(40)

In [ ]:
arr[1:4]

array([20, 30, 40])

In [4]:
arr2d = np.array([[1,2,3],[3,4,5],[6,8,9]])
print(arr2d[1:,1:])

[[4 5]
 [8 9]]


In [ ]:
arr2d.shape

(3, 3)

In [ ]:
arr2d.size

9

In [5]:
print(arr2d[0:,0:],)

[[1 2 3]
 [3 4 5]
 [6 8 9]]


In [7]:
#Here we declare as row [0, 0, 1, 1,2,2] and [1, 2, 0, 1,1,2] as col means o row col 1,2 1 row col 0, 1 2 row col 1,2
result = arr2d[
    [0, 0, 1, 1,2,2],
    [1, 2, 0, 1,1,2]
].reshape(3, 2)

print(result)


[[2 3]
 [3 4]
 [8 9]]


In [9]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
print(np.vstack((a,b,c)))
print(a+b+c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]


In [10]:
#Broadcasting
c = np.array([[1,2,3],[4,5,6]])
result = c+10
print(result)

[[11 12 13]
 [14 15 16]]


In [12]:
arr = np.array([1,2,3,4,5])
print(arr.dtype)
print(arr.sum())
print(arr.min())
print(arr.max())
print(arr.mean())

int64
15
1
5
3.0


In [33]:
A = np.array([[1,2,3],[5,6,7],[1,4,2]])
B = np.array([[6,4,2],[9,7,5],[3,5,9]])
print(A)
print(B)
result = np.dot(A,B)
print(np.linalg.det(A))
print(np.linalg.det(B))
reshaped = A.reshape(1,9)
print(reshaped)
print(result)
np.transpose (result)

[[1 2 3]
 [5 6 7]
 [1 4 2]]
[[6 4 2]
 [9 7 5]
 [3 5 9]]
19.999999999999996
11.999999999999968
[[1 2 3 5 6 7 1 4 2]]
[[ 33  33  39]
 [105  97 103]
 [ 48  42  40]]


array([[ 33, 105,  48],
       [ 33,  97,  42],
       [ 39, 103,  40]])

In [34]:
arr = np.array([[1],[2],[3]])
vector = np.array([10,20,30])
result = arr + vector
print(result)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [35]:
arr = np.array([3,2,1])
sorted_arr = np.sort(arr)
print(sorted_arr)
indices = np.argsort(arr)
print(indices)

[1 2 3]
[2 1 0]


In [37]:
large_arr = np.random.rand(1_000_000)
print(np.sum(large_arr))

499436.4307717322


In [38]:
arr= np.array([3,4,5])
np.save('array1.npy',arr)

In [39]:
loaded = np.load('array1.npy')
print(loaded)

[3 4 5]
