<a href="https://colab.research.google.com/github/hvjha/AWA/blob/Python/class_23.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
data= [2,4,5,6,7,8,9]


In [2]:
import numpy as np
print(np.mean(data))

5.857142857142857


In [3]:
print(np.median(data))

6.0


In [4]:
print(np.var(data))

4.979591836734694


In [5]:
print(np.std(data))

2.2314999074019015


In [6]:
print(np.sum(data))

41


In [7]:
print(np.prod(data))

120960


In [9]:
print(np.percentile(data,50))

6.0


In [10]:
data = [1,2,3,4,5]


In [11]:
np.cumsum(data)

array([ 1,  3,  6, 10, 15])

In [12]:
np.cumprod(data)

array([  1,   2,   6,  24, 120])

In [13]:
x = [1,2,3,4,5]
y= [2,4,6,8,10]
print(np.corrcoef(x,y))

[[1. 1.]
 [1. 1.]]


In [14]:
x = [1,2,3,4]
y= [4,3,2,1]
print(np.corrcoef(x,y))

[[ 1. -1.]
 [-1.  1.]]


In [15]:
normal_sample = np.random.normal(loc=0,scale=1,size=5)
print(normal_sample)

[-1.78593046 -1.59202094  0.87843884  2.18527566  1.01650974]


In [16]:
normal_sample = np.random.uniform(low=0,high=10,size=5)
print(normal_sample)

[0.16230827 4.58372562 0.92467727 3.29764905 6.66472296]
